#Build this image with: docker build --file Dockerfile_MasterServer -t lmpms:latest .
#Delete the image with the command: docker image rm lmpms:latest

#Create a container with: docker run -d -p 8700:8700 -p 8701:8701 --name lmpms lmpms:latest
#Create a container with with specific ports: docker run -d -p 8700:8700 -p 8701:8701 -e PORT=8700 -e HTTP_PORT=8701 --name lmpms lmpms:latest
#Attach to a container with: docker exec -it lmpms /bin/ash
#When inside a container, you can dettach with: CONTROL+P+Q
#Check logs with: docker logs -f lmpms

#Stop a container with: docker stop lmpms
#Start a container with: docker start lmpms
#Remove a container with: docker container rm lmpms

FROM alpine:3.9
RUN apk add --no-cache mono --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing

ENV LMP_URL https://luna-masterserver-endpoint.glitch.me/latest
ENV PORT 8700
ENV HTTP_PORT 8701
	
CMD wget $LMP_URL && unzip latest && cd LMPMasterServer && mono MasterServer.exe -p $PORT -g $HTTP_PORT