//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunaServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Bill Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Engineer
        ///brave = 0.5
        ///dumb = 0.800000012
        ///badS = False
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Bill_Kerman {
            get {
                return ResourceManager.GetString("Bill_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Bob Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Scientist
        ///brave = 0.300000012
        ///dumb = 0.100000001
        ///badS = False
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Bob_Kerman {
            get {
                return ResourceManager.GetString("Bob_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Jebediah Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Pilot
        ///brave = 0.5
        ///dumb = 0.5
        ///badS = True
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Jebediah_Kerman {
            get {
                return ResourceManager.GetString("Jebediah_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Valentina Kerman
        ///gender = Female
        ///type = Crew
        ///trait = Pilot
        ///brave = 0.550000012
        ///dumb = 0.400000006
        ///badS = True
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Valentina_Kerman {
            get {
                return ResourceManager.GetString("Valentina_Kerman", resourceCulture);
            }
        }
    }
}
