//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Bill Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Engineer
        ///brave = 0.5
        ///dumb = 0.800000012
        ///badS = False
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Bill_Kerman {
            get {
                return ResourceManager.GetString("Bill_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Bob Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Scientist
        ///brave = 0.300000012
        ///dumb = 0.100000001
        ///badS = False
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Bob_Kerman {
            get {
                return ResourceManager.GetString("Bob_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = CommNetScenario
        ///scene = 7, 8, 5, 6.
        /// </summary>
        internal static string CommNetScenario {
            get {
                return ResourceManager.GetString("CommNetScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ContractSystem
        ///scene = 7, 8, 5, 6
        ///update = 209.7130991000256
        ///version = 1.4.1
        ///WEIGHTS
        ///{
        ///	TourismContract = 30
        ///	SurveyContract = 30
        ///	StationContract = 30
        ///	SentinelContract = 30
        ///	SatelliteContract = 30
        ///	ISRUContract = 30
        ///	ExplorationContract = 30
        ///	BaseContract = 30
        ///	ARMContract = 30
        ///	RecoverAsset = 30
        ///	PlantFlag = 30
        ///	PartTest = 30
        ///	GrandTour = 30
        ///	CollectScience = 30
        ///	Eeloo = 30
        ///	Dres = 30
        ///	Pol = 30
        ///	Gilly = 30
        ///	Tylo = 30
        ///	Bop = 30
        ///	Vall = 30
        ///	Laythe = 30
        ///	Jool = 30
        ///	Ike =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContractSystem {
            get {
                return ResourceManager.GetString("ContractSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Funding
        ///scene = 7, 8, 5, 6
        ///funds = 25000.
        /// </summary>
        internal static string Funding {
            get {
                return ResourceManager.GetString("Funding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Jebediah Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Pilot
        ///brave = 0.5
        ///dumb = 0.5
        ///badS = True
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Jebediah_Kerman {
            get {
                return ResourceManager.GetString("Jebediah_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = PartUpgradeManager
        ///scene = 6, 5, 7
        ///UPGRADES
        ///{
        ///	Unlocks
        ///	{
        ///	}
        ///	Enableds
        ///	{
        ///	}
        ///}.
        /// </summary>
        internal static string PartUpgradeManager {
            get {
                return ResourceManager.GetString("PartUpgradeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ProgressTracking
        ///scene = 7, 8, 5
        ///Progress
        ///{
        ///}.
        /// </summary>
        internal static string ProgressTracking {
            get {
                return ResourceManager.GetString("ProgressTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Reputation
        ///scene = 7, 8, 5, 6
        ///rep = 0.
        /// </summary>
        internal static string Reputation {
            get {
                return ResourceManager.GetString("Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ResearchAndDevelopment
        ///scene = 7, 8, 5, 6
        ///sci = 0
        ///Tech
        ///{
        ///	id = start
        ///	state = Available
        ///	cost = 0
        ///	part = basicFin
        ///	part = mk1pod
        ///	part = solidBooster.sm
        ///	part = GooExperiment
        ///	part = trussPiece1x
        ///	part = parachuteSingle
        ///}.
        /// </summary>
        internal static string ResearchAndDevelopment {
            get {
                return ResourceManager.GetString("ResearchAndDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ResourceScenario
        ///scene = 7, 8, 5, 6, 21
        ///RESOURCE_SETTINGS
        ///{
        ///	GameSeed = 162051528
        ///	MaxDeltaTime = 21600
        ///}.
        /// </summary>
        internal static string ResourceScenario {
            get {
                return ResourceManager.GetString("ResourceScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ScenarioAchievements
        ///scene = 7, 8, 5, 6.
        /// </summary>
        internal static string ScenarioAchievements {
            get {
                return ResourceManager.GetString("ScenarioAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ScenarioContractEvents
        ///scene = 7, 8, 5
        ///id = 1765692878.
        /// </summary>
        internal static string ScenarioContractEvents {
            get {
                return ResourceManager.GetString("ScenarioContractEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ScenarioDestructibles
        ///scene = 5, 7, 6, 8
        ///SpaceCenter/Administration/Facility/mainBuilding
        ///{
        ///	intact = True
        ///}
        ///SpaceCenter/AstronautComplex/Facility/building
        ///{
        ///	intact = True
        ///}
        ///SpaceCenter/LaunchPad/Facility/LaunchPadMedium/ksp_pad_cylTank
        ///{
        ///	intact = True
        ///}
        ///SpaceCenter/LaunchPad/Facility/LaunchPadMedium/ksp_pad_launchPad
        ///{
        ///	intact = True
        ///}
        ///SpaceCenter/LaunchPad/Facility/LaunchPadMedium/ksp_pad_sphereTank
        ///{
        ///	intact = True
        ///}
        ///SpaceCenter/LaunchPad/Facility/LaunchPadMedium/ksp_pad_wa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScenarioDestructibles {
            get {
                return ResourceManager.GetString("ScenarioDestructibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ScenarioNewGameIntro
        ///scene = 7, 8, 5, 6
        ///kscComplete = True
        ///editorComplete = True
        ///tsComplete = True.
        /// </summary>
        internal static string ScenarioNewGameIntro {
            get {
                return ResourceManager.GetString("ScenarioNewGameIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = ScenarioUpgradeableFacilities
        ///scene = 5, 6, 7, 8
        ///SpaceCenter/LaunchPad
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/Runway
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/VehicleAssemblyBuilding
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/SpaceplaneHangar
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/TrackingStation
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/AstronautComplex
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/MissionControl
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/ResearchAndDevelopment
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/Administration
        ///{
        ///	lvl = 0
        ///}
        ///SpaceCenter/FlagPole
        ///{
        ///	lvl = 0
        ///}.
        /// </summary>
        internal static string ScenarioUpgradeableFacilities {
            get {
                return ResourceManager.GetString("ScenarioUpgradeableFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = SentinelScenario
        ///scene = 7, 8, 5
        ///NextSpawnTime = 26612.162481160907.
        /// </summary>
        internal static string SentinelScenario {
            get {
                return ResourceManager.GetString("SentinelScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = StrategySystem
        ///scene = 7, 8, 5, 6
        ///STRATEGIES
        ///{
        ///}.
        /// </summary>
        internal static string StrategySystem {
            get {
                return ResourceManager.GetString("StrategySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Valentina Kerman
        ///gender = Female
        ///type = Crew
        ///trait = Pilot
        ///brave = 0.550000012
        ///dumb = 0.400000006
        ///badS = True
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Valentina_Kerman {
            get {
                return ResourceManager.GetString("Valentina_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = VesselRecovery
        ///scene = 5, 7, 8, 6.
        /// </summary>
        internal static string VesselRecovery {
            get {
                return ResourceManager.GetString("VesselRecovery", resourceCulture);
            }
        }
    }
}
