//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Bill Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Engineer
        ///brave = 0.5
        ///dumb = 0.800000012
        ///badS = False
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Bill_Kerman {
            get {
                return ResourceManager.GetString("Bill_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Bob Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Scientist
        ///brave = 0.300000012
        ///dumb = 0.100000001
        ///badS = False
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Bob_Kerman {
            get {
                return ResourceManager.GetString("Bob_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML /&gt;.
        /// </summary>
        internal static string CommNetScenario {
            get {
                return ResourceManager.GetString("CommNetScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;ContractSystem&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5, 6&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;update&quot;&gt;209.7130991000256&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;version&quot;&gt;1.4.1&lt;/Parameter&gt;
        ///  &lt;Node name=&quot;WEIGHTS&quot;&gt;
        ///    &lt;Parameter name=&quot;TourismContract&quot;&gt;30&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;SurveyContract&quot;&gt;30&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;StationContract&quot;&gt;30&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;SentinelContract&quot;&gt;30&lt;/Parameter&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContractSystem {
            get {
                return ResourceManager.GetString("ContractSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;Funding&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5, 6&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;funds&quot;&gt;25000&lt;/Parameter&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string Funding {
            get {
                return ResourceManager.GetString("Funding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Jebediah Kerman
        ///gender = Male
        ///type = Crew
        ///trait = Pilot
        ///brave = 0.5
        ///dumb = 0.5
        ///badS = True
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Jebediah_Kerman {
            get {
                return ResourceManager.GetString("Jebediah_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;PartUpgradeManager&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;6, 5, 7&lt;/Parameter&gt;
        ///  &lt;Node name=&quot;UPGRADES&quot;&gt;
        ///    &lt;Node name=&quot;Unlocks&quot; /&gt;
        ///    &lt;Node name=&quot;Enableds&quot; /&gt;
        ///  &lt;/Node&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string PartUpgradeManager {
            get {
                return ResourceManager.GetString("PartUpgradeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;ProgressTracking&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5&lt;/Parameter&gt;
        ///  &lt;Node name=&quot;Progress&quot; /&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string ProgressTracking {
            get {
                return ResourceManager.GetString("ProgressTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;Reputation&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5, 6&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;rep&quot;&gt;0&lt;/Parameter&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string Reputation {
            get {
                return ResourceManager.GetString("Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;ResearchAndDevelopment&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5, 6&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;sci&quot;&gt;0&lt;/Parameter&gt;
        ///  &lt;Node name=&quot;Tech&quot;&gt;
        ///    &lt;Parameter name=&quot;id&quot;&gt;start&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;state&quot;&gt;Available&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;cost&quot;&gt;0&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;part&quot;&gt;basicFin&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;part&quot;&gt;mk1pod&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;part&quot;&gt;solidBooster.sm&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResearchAndDevelopment {
            get {
                return ResourceManager.GetString("ResearchAndDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;ResourceScenario&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5, 6, 21&lt;/Parameter&gt;
        ///  &lt;Node name=&quot;RESOURCE_SETTINGS&quot;&gt;
        ///    &lt;Parameter name=&quot;GameSeed&quot;&gt;162051528&lt;/Parameter&gt;
        ///    &lt;Parameter name=&quot;MaxDeltaTime&quot;&gt;21600&lt;/Parameter&gt;
        ///  &lt;/Node&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string ResourceScenario {
            get {
                return ResourceManager.GetString("ResourceScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;ScenarioAchievements&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5, 6&lt;/Parameter&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string ScenarioAchievements {
            get {
                return ResourceManager.GetString("ScenarioAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;ScenarioContractEvents&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;id&quot;&gt;1765692878&lt;/Parameter&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string ScenarioContractEvents {
            get {
                return ResourceManager.GetString("ScenarioContractEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;ScenarioDestructibles&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;5, 7, 6, 8&lt;/Parameter&gt;
        ///  &lt;Node name=&quot;SpaceCenter/Administration/Facility/mainBuilding&quot;&gt;
        ///    &lt;Parameter name=&quot;intact&quot;&gt;True&lt;/Parameter&gt;
        ///  &lt;/Node&gt;
        ///  &lt;Node name=&quot;SpaceCenter/AstronautComplex/Facility/building&quot;&gt;
        ///    &lt;Parameter name=&quot;intact&quot;&gt;True&lt;/Parameter&gt;
        ///  &lt;/Node&gt;
        ///  &lt;Node name=&quot;SpaceCenter/LaunchPad/Facility/LaunchPadMedium/ksp_pad_cylTank&quot;&gt;
        ///    &lt;Paramete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScenarioDestructibles {
            get {
                return ResourceManager.GetString("ScenarioDestructibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;ScenarioUpgradeableFacilities&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;5, 6, 7, 8&lt;/Parameter&gt;
        ///  &lt;Node name=&quot;SpaceCenter/LaunchPad&quot;&gt;
        ///    &lt;Parameter name=&quot;lvl&quot;&gt;0&lt;/Parameter&gt;
        ///  &lt;/Node&gt;
        ///  &lt;Node name=&quot;SpaceCenter/Runway&quot;&gt;
        ///    &lt;Parameter name=&quot;lvl&quot;&gt;0&lt;/Parameter&gt;
        ///  &lt;/Node&gt;
        ///  &lt;Node name=&quot;SpaceCenter/VehicleAssemblyBuilding&quot;&gt;
        ///    &lt;Parameter name=&quot;lvl&quot;&gt;0&lt;/Parameter&gt;
        ///  &lt;/Node&gt;
        ///  &lt;Node name=&quot;SpaceCenter/SpaceplaneHangar&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScenarioUpgradeableFacilities {
            get {
                return ResourceManager.GetString("ScenarioUpgradeableFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;SentinelScenario&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;NextSpawnTime&quot;&gt;26612.162481160907&lt;/Parameter&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string SentinelScenario {
            get {
                return ResourceManager.GetString("SentinelScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;StrategySystem&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;7, 8, 5, 6&lt;/Parameter&gt;
        ///  &lt;Node name=&quot;STRATEGIES&quot; /&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string StrategySystem {
            get {
                return ResourceManager.GetString("StrategySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name = Valentina Kerman
        ///gender = Female
        ///type = Crew
        ///trait = Pilot
        ///brave = 0.550000012
        ///dumb = 0.400000006
        ///badS = True
        ///veteran = True
        ///tour = False
        ///state = Available
        ///inactive = False
        ///inactiveTimeEnd = 0
        ///gExperienced = 0
        ///outDueToG = False
        ///ToD = 0
        ///idx = -1
        ///extraXP = 0
        ///CAREER_LOG
        ///{
        ///	flight = 0
        ///}
        ///FLIGHT_LOG
        ///{
        ///	flight = 0
        ///}.
        /// </summary>
        internal static string Valentina_Kerman {
            get {
                return ResourceManager.GetString("Valentina_Kerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;LMPConfigNodeToXML&gt;
        ///  &lt;Parameter name=&quot;name&quot;&gt;VesselRecovery&lt;/Parameter&gt;
        ///  &lt;Parameter name=&quot;scene&quot;&gt;5, 7, 8, 6&lt;/Parameter&gt;
        ///&lt;/LMPConfigNodeToXML&gt;.
        /// </summary>
        internal static string VesselRecovery {
            get {
                return ResourceManager.GetString("VesselRecovery", resourceCulture);
            }
        }
    }
}
