namespace LunaCommon.Flags
{
    public class DefaultFlags
    {
        public static string[] DefaultFlagList = {
            "LunaMultiplayer/Flags/lmp",
            "LunaMultiplayer/Flags/republican_spain",
            "LunaMultiplayer/Flags/skwod",
            "Squad/Flags/09",
            "Squad/Flags/B612_Foundation_flag",
            "Squad/Flags/blorbs",
            "Squad/Flags/bullseye",
            "Squad/Flags/capsule",
            "Squad/Flags/circles",
            "Squad/Flags/default",
            "Squad/Flags/esa_dark_blue",
            "Squad/Flags/hexagon",
            "Squad/Flags/hexagonCircles",
            "Squad/Flags/kerbal1",
            "Squad/Flags/kerbal2",
            "Squad/Flags/kerbin",
            "Squad/Flags/kerbinmunflag",
            "Squad/Flags/line",
            "Squad/Flags/minimalistic",
            "Squad/Flags/NASA",
            "Squad/Flags/orbit",
            "Squad/Flags/orbs",
            "Squad/Flags/retro",
            "Squad/Flags/rings",
            "Squad/Flags/rocketScience",
            "Squad/Flags/rocketScience OUT OF DATE",
            "Squad/Flags/rocketScience",
            "Squad/Flags/rocketScience_originalsize",
            "Squad/Flags/satellite",
            "Squad/Flags/Sentinel_Flag",
            "Squad/Flags/spheres",
            "Squad/Flags/squadLogo",
            "Squad/Flags/squadLogo2",
            "Squad/Flags/stripes",
            "Squad/Flags/trees",
            "Squad/Flags/trippy",
            "Squad/Flags/uk_space_agency",
        };
    }
}
