using LmpClient.Base;
using LmpClient.Localization;
using LmpClient.Systems.SettingsSys;
using LmpClient.Utilities;
using LmpCommon.Enums;
using LmpCommon.Time;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace LmpClient.Systems.CraftLibrary
{
    public class CraftLibrarySystem : MessageSystem<CraftLibrarySystem, CraftLibraryMessageSender, CraftLibraryMessageHandler>
    {
        #region Fields and properties

        private static readonly string SaveFolder = CommonUtil.CombinePaths(MainSystem.KspPath, "saves", "LunaMultiplayer");

        private static DateTime _lastRequest = DateTime.MinValue;
        private static readonly SemaphoreSlim _craftIoSemaphore = new SemaphoreSlim(1, 1);

        public ConcurrentDictionary<string, ConcurrentDictionary<string, CraftBasicEntry>> CraftInfo { get; } = new ConcurrentDictionary<string, ConcurrentDictionary<string, CraftBasicEntry>>();
        public ConcurrentDictionary<string, ConcurrentDictionary<string, CraftEntry>> CraftDownloaded { get; } = new ConcurrentDictionary<string, ConcurrentDictionary<string, CraftEntry>>();

        public List<CraftEntry> OwnCrafts { get; private set; } = new List<CraftEntry>();

        public ConcurrentQueue<string> DownloadedCraftsNotification { get; } = new ConcurrentQueue<string>();
        public List<string> FoldersWithNewContent { get; } = new List<string>();
        public bool NewContent => FoldersWithNewContent.Any();

        #endregion

        #region Base overrides

        public override string SystemName { get; } = nameof(CraftLibrarySystem);

        protected override bool ProcessMessagesInUnityThread => false;

        protected override void OnEnabled()
        {
            base.OnEnabled();
            RefreshOwnCrafts();
            MessageSender.SendRequestFoldersMsg();
            SetupRoutine(new RoutineDefinition(1000, RoutineExecution.Update, NotifyDownloadedCrafts));
        }

        private void NotifyDownloadedCrafts()
        {
            while (DownloadedCraftsNotification.TryDequeue(out var message))
                LunaScreenMsg.PostScreenMessage($"({message}) {LocalizationContainer.ScreenText.CraftSaved}", 5f, ScreenMessageStyle.UPPER_CENTER);
        }

        protected override void OnDisabled()
        {
            base.OnDisabled();
            CraftInfo.Clear();
            CraftDownloaded.Clear();
        }

        #endregion

        #region Public methods

        /// <summary>
        /// Refreshes the list of our own crafts in the background
        /// </summary>
        public void RefreshOwnCrafts()
        {
            OwnCrafts.Clear();
            
            LoadCraftsFromFolder(CommonUtil.CombinePaths(SaveFolder, "Ships", "VAB"), CraftType.Vab);
            LoadCraftsFromFolder(CommonUtil.CombinePaths(SaveFolder, "Ships", "SPH"), CraftType.Sph);
            LoadCraftsFromFolder(CommonUtil.CombinePaths(SaveFolder, "Subassemblies"), CraftType.Subassembly);
        }

        /// <summary>
        /// Loads every shareable craft file from the specified folder.
        /// Only .craft files are considered; sidecar files generated by KSP (e.g. .loadmeta)
        /// are intentionally ignored so each ship is represented by a single entry.
        /// </summary>
        private void LoadCraftsFromFolder(string folder, CraftType craftType)
        {
            if (!Directory.Exists(folder)) return;

            foreach (var file in Directory.GetFiles(folder, "*.craft"))
            {
                var data = File.ReadAllBytes(file);
                OwnCrafts.Add(new CraftEntry
                {
                    CraftName = Path.GetFileNameWithoutExtension(file),
                    CraftType = craftType,
                    FolderName = SettingsSystem.CurrentSettings.PlayerName,
                    CraftData = data,
                    CraftNumBytes = data.Length
                });
            }
        }

        /// <summary>
        /// Saves a craft to the hard drive asynchronously
        /// </summary>
        public void SaveCraftToDisk(CraftEntry craft)
        {
            Task.Run(async () =>
            {
                await _craftIoSemaphore.WaitAsync();
                try
                {
                    string folder;
                    switch (craft.CraftType)
                    {
                        case CraftType.Vab:
                            folder = CommonUtil.CombinePaths(SaveFolder, "Ships", "VAB");
                            break;
                        case CraftType.Sph:
                            folder = CommonUtil.CombinePaths(SaveFolder, "Ships", "SPH");
                            break;
                        case CraftType.Subassembly:
                            folder = CommonUtil.CombinePaths(SaveFolder, "Subassemblies");
                            break;
                        default:
                            throw new ArgumentOutOfRangeException();
                    }

                    var path = CommonUtil.CombinePaths(folder, $"{craft.CraftName}.craft");
                    File.WriteAllBytes(path, craft.CraftData);

                    //Add it to the queue notification as we are in another thread
                    DownloadedCraftsNotification.Enqueue(craft.CraftName);
                }
                catch (Exception ex)
                {
                    LunaLog.LogError($"[LMP]: Error saving craft to disk: {ex.Message}");
                }
                finally
                {
                    _craftIoSemaphore.Release();
                }
            });
        }

        /// <summary>
        /// Sends a craft to the server if possible
        /// </summary>
        public void SendCraft(CraftEntry craft)
        {
            if (TimeUtil.IsInInterval(ref _lastRequest, SettingsSystem.ServerSettings.MinCraftLibraryRequestIntervalMs))
            {
                MessageSender.SendCraftMsg(craft);
                LunaScreenMsg.PostScreenMessage(LocalizationContainer.ScreenText.CraftUploaded, 10f, ScreenMessageStyle.UPPER_CENTER);
            }
            else
            {
                var msg = LocalizationContainer.ScreenText.CraftLibraryInterval.Replace("$1",
                    TimeSpan.FromMilliseconds(SettingsSystem.ServerSettings.MinCraftLibraryRequestIntervalMs).TotalSeconds.ToString(CultureInfo.InvariantCulture));

                LunaScreenMsg.PostScreenMessage(msg, 20f, ScreenMessageStyle.UPPER_CENTER);
            }
        }

        /// <summary>
        /// Request a craft to the server if possible
        /// </summary>
        public void RequestCraft(CraftBasicEntry craft)
        {
            if (TimeUtil.IsInInterval(ref _lastRequest, SettingsSystem.ServerSettings.MinCraftLibraryRequestIntervalMs))
            {
                MessageSender.SendRequestCraftMsg(craft);
            }
            else
            {
                var msg = LocalizationContainer.ScreenText.CraftLibraryInterval.Replace("$1",
                    TimeSpan.FromMilliseconds(SettingsSystem.ServerSettings.MinCraftLibraryRequestIntervalMs).TotalSeconds.ToString(CultureInfo.InvariantCulture));

                LunaScreenMsg.PostScreenMessage(msg, 20f, ScreenMessageStyle.UPPER_CENTER);
            }
        }

        #endregion

        public void RequestCraftListIfNeeded(string selectedFolder)
        {
            if (FoldersWithNewContent.Contains(selectedFolder))
            {
                FoldersWithNewContent.Remove(selectedFolder);
                MessageSender.SendRequestCraftListMsg(selectedFolder);
                return;
            }

            if (CraftInfo.GetOrAdd(selectedFolder, new ConcurrentDictionary<string, CraftBasicEntry>()).Count == 0)
                MessageSender.SendRequestCraftListMsg(selectedFolder);
        }
    }
}
